export const MIME_TO_CATEGORY: Record<string, string> = {
  // Document
  "application/pdf": "document",
  "application/msword": "document",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "document",
  "application/vnd.ms-excel": "document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "document",
  "application/vnd.ms-powerpoint": "document",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "document",
  "text/plain": "document",
  "text/csv": "document",
  "application/rtf": "document",
  "text/rtf": "document",
  "application/vnd.oasis.opendocument.text": "document",
  "application/vnd.oasis.opendocument.spreadsheet": "document",
  "application/vnd.oasis.opendocument.presentation": "document",

  // Image
  "image/png": "image",
  "image/jpeg": "image",
  "image/gif": "image",
  "image/webp": "image",
  "image/svg+xml": "image",
  "image/bmp": "image",
  "image/x-icon": "image",
  "image/tiff": "image",
  "image/avif": "image",

  // Audio
  "audio/mpeg": "audio",
  "audio/wav": "audio",
  "audio/ogg": "audio",
  "audio/flac": "audio",
  "audio/aac": "audio",
  "audio/webm": "audio",
  "audio/mp4": "audio",
  "audio/x-ms-wma": "audio",
  "audio/opus": "audio",

  // Video
  "video/mp4": "video",
  "video/webm": "video",
  "video/ogg": "video",
  "video/quicktime": "video",
  "video/x-msvideo": "video",
  "video/x-ms-wmv": "video",
  "video/x-flv": "video",
  "video/mpeg": "video",
  "video/3gpp": "video",

  // Executbles
  "application/x-msdownload": "executable",
  "application/x-executable": "executable",
  "application/x-sh": "executable",
  "application/x-msdos-program": "executable",
  "application/x-dmg": "executable",
  "application/x-debian-package": "executable",
  "application/x-rpm": "executable",
  "application/vnd.android.package-archive": "executable",

  // Compressed
  "application/zip": "compressed",
  "application/x-rar-compressed": "compressed",
  "application/x-7z-compressed": "compressed",
  "application/gzip": "compressed",
  "application/x-tar": "compressed",
  "application/x-bzip2": "compressed",
  "application/x-xz": "compressed",
  "application/zstd": "compressed",

  // code
  "text/javascript": "code",
  "application/json": "code",
  "text/html": "code",
  "text/css": "code",
  "text/x-python": "code",
  "text/x-java-source": "code",
  "text/x-c": "code",
  "text/x-c++": "code",
  "text/x-go": "code",
  "text/x-rust": "code",
  "text/x-php": "code",
  "text/x-ruby": "code",
  "text/x-swift": "code",
  "text/x-kotlin": "code",
  "text/x-scala": "code",
  "application/xml": "code",
  "text/x-sql": "code",
  "text/markdown": "code",
  "application/x-yaml": "code",

  // Font
  "font/ttf": "font",
  "font/otf": "font",
  "font/woff": "font",
  "font/woff2": "font",
  "application/vnd.ms-fontobject": "font",
};