name: Deploy Storage App

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "apps/cdk-app/**"
      - "apps/cdk/**"

jobs:
  release:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      #AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # Al estar en el root, el contexto y el file son locales al inicio
          context: . 
          file: ./Dockerfile 
          push: true
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:${{ github.sha }}
            ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest




      - name: CDK Diff
        working-directory: apps/cdk-app
        run: pnpm cdk diff --all
        env:
          IMAGE_TAG: ${{ github.sha }}
          AUTH-SECRET: ${{ secrets.AUTH_SECRET }}

      - name: CDK DEPLOY
        working-directory: apps/cdk-app
        env:
          IMAGE_TAG: ${{ github.sha }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET}}
        run: pnpm cdk deploy --all --require-approval never
